# Generated by Django 4.0.6 on 2022-09-29 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tweet_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='id_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfollowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allPosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='network.tweet')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
